module.exports = {
  parser: 'babel-eslint',
  extends: [
    'airbnb',
    'plugin:react/recommended',
    'prettier',
    'prettier/react',
    'plugin:prettier/recommended',
  ],
  plugins: ['jest', 'react-hooks', 'prettier'],
  env: {
    browser: true,
    node: true,
    es6: true,
    worker: true,
    'jest/globals': true,
  },
  rules: {
    'arrow-body-style': 0,
    'class-methods-use-this': 0,
    'func-names': 0,
    'function-paren-newline': 0,
    'global-require': 0,
    'import/no-dynamic-require': 0,
    'import/no-extraneous-dependencies': [2, {}],
    'import/prefer-default-export': 1,
    'jsx-a11y/anchor-is-valid': 0,
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/href-no-hash': 0,
    'linebreak-style': 0,
    'lines-between-class-members': 0,
    'no-console': 1,
    'no-irregular-whitespace': 0,
    'no-param-reassign': 0,
    'no-restricted-globals': 0,
    'no-underscore-dangle': 0,
    'no-unused-vars': 1,
    'object-curly-spacing': 0,
    'prefer-arrow-callback': 0,
    'prefer-template': 1,
    'prefer-destructuring': 0,
    'react/forbid-prop-types': 0,
    'react-hooks/rules-of-hooks': 2,
    'react-hooks/exhaustive-deps': 2,
    'react/jsx-filename-extension': 0,
    'react/jsx-props-no-spreading': 0,
  },
  settings: {
    'import/resolver': {
      'babel-module': {
        root: ['./src'],
      },
    },
  },
};
